import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Camera,Check,FlaskConical,Layers,ShieldCheck,Users,CalendarDays,BookOpen,Radio,ChevronRight} from 'lucide-react';
import type {Lang} from './content';

type Props={lang:Lang};
const text=(lang:Lang)=>(en:string,zh:string)=>lang==='zh'?zh:en;
const image=(file:string)=>`/media/${file}`;

function WorkbenchHeader({lang,area}:{lang:Lang;area:string}){
 const t=text(lang);
 return <div className="wb-header"><div className="wb-brand"><img src="/brand/pheno-logo.png" alt="Pheno"/><span>{area}</span></div><span className="wb-mode">{t('Interface recreation · demo data','界面重绘 · 演示数据')}</span></div>;
}

export function ExperimentDesigner({lang}:Props){
 const t=text(lang),[step,setStep]=useState(0);
 const steps=[{title:t('Prepare samples','准备样品'),code:'01',details:[[t('Sample group','样品组'),'DEMO A–C'],[t('Container','容器'),t('Labelled sample vials','已标记的样品瓶')]],note:t('Check sample identity before transfer.','转移前核对样品身份。')},{title:t('Transfer & mix','转移与混合'),code:'02',details:[[t('Workstation','工作站'),'GB-01'],[t('Record','记录'),t('Actual conditions + observation','实际条件与观察记录')]],note:t('Link the camera segment to this procedure step.','将相机片段关联到当前实验步骤。')},{title:t('Characterize','表征'),code:'03',details:[[t('Evidence','证据'),t('Instrument file + image','仪器文件与图像')],[t('Comparison','比较'),t('Across samples A–C','比较样品 A–C')]],note:t('Keep the result attached to its sample and conditions.','将结果与对应样品及实验条件关联。')}];
 return <section className="workbench designer-demo" aria-label={t('Phenolab experiment design demonstration','Phenolab 实验设计演示')}>
 <WorkbenchHeader lang={lang} area="Phenolab"/>
 <div className="wb-toolbar"><div><span className="wb-kicker">DEMO / EXP-024</span><h4>{t('From protocol to evidence','从实验方案到证据')}</h4></div><span className="wb-status">{t('Design review','方案审核')}</span></div>
 <div className="designer-grid"><aside className="process-library"><span className="wb-kicker">{t('PROCESS LIBRARY','工艺库')}</span>{[t('Sample preparation','样品制备'),t('Cleaning / washing','清洗'),t('Surface treatment','表面处理'),t('Spin coating','旋涂'),t('Thermal anneal','热退火'),t('Characterization','表征')].map((name,i)=><div key={name}><FlaskConical size={14}/>{name}<span>0{i+1}</span></div>)}</aside>
 <div className="designer-main"><div className="science-record">{[[t('Observation','观察'),t('Three samples need a comparable preparation record.','三个样品需要可比较的制备记录。')],[t('Question','问题'),t('Which process differences explain the result?','哪些工艺差异能够解释结果？')],[t('Hypothesis','假设'),t('To be reviewed by the researcher.','待研究人员审核。')]].map(([label,value])=><div key={label}><strong>{label}</strong><span>{value}</span></div>)}</div>
 <div className="test-plan"><Layers size={18}/><div><strong>{t('Compare samples A · B · C','比较样品 A · B · C')}</strong><p>{t('Keep planned conditions and actual observations together.','同时保留计划条件与实际观察。')}</p></div></div>
 <div className="wb-section-label">{t('Process flow','实验流程')}<span>{t('Select a step to inspect','选择步骤以查看详情')}</span></div>
 <div className="process-steps">{steps.map((s,i)=><button key={s.code} onClick={()=>setStep(i)} aria-pressed={step===i}><span>{s.code}</span><strong>{s.title}</strong><ChevronRight size={16}/></button>)}</div>
 <div className="evidence-attachments"><span className="wb-kicker">{t('LINKED EVIDENCE','关联证据')}</span><div><Camera size={17}/>{t('Camera segment','相机片段')}<span>GB-01</span></div><div><BookOpen size={17}/>{t('Instrument result','仪器结果')}<span>A · B · C</span></div></div></div>
 <aside className="step-inspector"><span className="wb-kicker">{t('STEP INSPECTOR','步骤详情')} / {steps[step].code}</span><h4>{steps[step].title}</h4>{steps[step].details.map(([k,v])=><div className="inspector-field" key={k}><span>{k}</span><strong>{v}</strong></div>)}<p>{steps[step].note}</p><span className="review-tag"><ShieldCheck size={16}/>{t('Researcher review','研究人员审核')}</span></aside></div>
 <div className="wb-footer">{t('Recreated from the current Phenolab design language. Illustrative experiment; camera linkage is a proposed extension.','按当前 Phenolab 设计语言重绘。实验内容为示例；相机片段关联为拟议扩展。')}</div>
 </section>;
}

export function CaptureWorkbench({lang}:Props){
 const t=text(lang),[objects,setObjects]=useState(true),[hands,setHands]=useState(true),[panel,setPanel]=useState<'frame'|'dataset'>('frame');
 return <section className="workbench capture-workbench" aria-label={t('Glovebox capture data concept','手套箱采集数据概念')}>
 <WorkbenchHeader lang={lang} area={t('Phenolab / Capture review','Phenolab / 采集审核')}/>
 <div className="wb-toolbar"><div><span className="wb-kicker">DEMO / GB-01 / TAKE-008</span><h4>{t('A demonstration becomes structured evidence.','让操作示范成为结构化证据。')}</h4></div><span className="wb-status">{t('Concept interface','概念界面')}</span></div>
 <div className="wb-view-tabs"><button aria-pressed={panel==='frame'} onClick={()=>setPanel('frame')}>{t('Inspect a frame','查看画面')}</button><button aria-pressed={panel==='dataset'} onClick={()=>setPanel('dataset')}>{t('Training record','训练记录')}</button></div>
 {panel==='frame'?<div className="capture-grid"><div><div className="camera-viewport"><img src={image('phenolab-camera-frame.png')} alt={t('Generated interior view: two gloved hands transfer a sample vial beside a rack','生成的手套箱内部视图：双手在样品架旁转移样品瓶')}/><span className="camera-id">CAM 01 <span>{t('Interior view · concept','内部视角 · 概念')}</span></span>
 {hands&&<><div className="annotation hand-a"><span>{t('Gloved hand · left','戴手套的左手')}</span></div><div className="annotation hand-b"><span>{t('Gloved hand · right','戴手套的右手')}</span></div></>}
 {objects&&<><div className="annotation vial"><span>{t('Sample vial','样品瓶')}</span></div><div className="annotation rack"><span>{t('Sample rack','样品架')}</span></div></>}
 <span className="frame-label">{t('Illustrative annotation · not detector output','示意标注 · 非检测模型输出')}</span></div>
 <div className="layer-controls"><span>{t('View layers','显示图层')}</span><label><input type="checkbox" checked={objects} onChange={e=>setObjects(e.target.checked)}/>{t('Objects','物体')}</label><label><input type="checkbox" checked={hands} onChange={e=>setHands(e.target.checked)}/>{t('Hands','手部区域')}</label></div>
 <div className="capture-events"><span className="wb-kicker">{t('PROPOSED TASK LABELS','拟议任务标签')}</span><div>{[t('Approach sample','接近样品'),t('Grasp & transfer','抓取与转移'),t('Place in rack','放入样品架')].map((s,i)=><span className={i===1?'selected':''} key={s}><b>0{i+1}</b>{s}</span>)}</div><p>{t('One still frame is illustrated here; action labels require review across the full sequence.','此处展示单帧示意；动作标签需结合完整时序审核。')}</p></div></div>
 <aside className="capture-detail"><div className="wb-section-label">{t('The record behind the image','图像背后的记录')}</div>{[[t('Linked sample','关联样品'),'DEMO-B'],[t('Procedure step','实验步骤'),t('Transfer & mix','转移与混合')],[t('Required evidence','所需证据'),t('Synchronized multi-view frames','同步多视角画面')],[t('Annotation status','标注状态'),t('Awaiting human review','待人工审核')]].map(([k,v])=><div className="inspector-field" key={k}><span>{k}</span><strong>{v}</strong></div>)}<div className="capture-note"><ShieldCheck size={20}/><p>{t('Retain timestamps, calibration and source frames alongside each reviewed label.','为每条审核后的标签保留时间戳、标定信息和来源画面。')}</p></div></aside></div>:<div className="training-record"><div><span className="wb-kicker">{t('DEMONSTRATION DATASET','操作示范数据集')}</span><h4>{t('Traceable examples for learning a task.','可追溯的任务学习样例。')}</h4><p>{t('Multi-view video, hand–object relationships and reviewed task phases provide the demonstration layer. Robot joint actions, embodiment calibration and task-success checks are additional requirements.','多视角视频、手与物体的关系，以及经审核的任务阶段构成示范层；仍需补充机器人关节动作、机体标定与任务成功验证。')}</p></div><div className="record-fields">{[[t('Inputs','输入'),t('Frames · timestamps · camera calibration','画面 · 时间戳 · 相机标定')],[t('Labels','标签'),t('Objects · hand regions · task phases','物体 · 手部区域 · 任务阶段')],[t('Links','关联'),t('Sample → procedure → evidence','样品 → 步骤 → 证据')],[t('Robot validation','机器人验证'),t('Separate action data + supervised trials','独立动作数据与受监督试验')]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></div>}
 <div className="wb-footer">{t('R&D concept. Camera images alone do not provide force, torque or verified robot-control actions.','研发概念。仅凭相机画面无法获得力、力矩或已验证的机器人控制动作。')}</div></section>;
}

export function PhenolabEvidence({lang}:Props){
 const t=text(lang);
 return <div className="application-evidence"><div className="evidence-heading"><span className="eyebrow">{t('The next capture layer','下一层采集能力')}</span><h4>{t('Learn from the hands doing the science.','从科研操作中学习。')}</h4><p>{t('A proposed path from human demonstration to reviewed data and dexterous robotic work.','从人工操作示范，到审核后的数据，再到灵巧机械手科研作业的拟议路径。')}</p></div>
 <div className="hardware-pair"><figure><a href={image('phenolab-glovebox-capture.png')} target="_blank" rel="noreferrer"><img src={image('phenolab-glovebox-capture.png')} loading="lazy" alt={t('Concept glovebox with three wired cameras and an edge computer capturing human demonstrations','三台有线相机与边缘计算设备采集人工操作示范的手套箱概念')}/></a><figcaption><strong>01 / {t('Record the demonstration','记录操作示范')}</strong>{t('Wired camera views and a local capture computer. Hardware concept rendering.','多视角有线相机与本地采集计算机。硬件概念渲染。')}</figcaption></figure><figure><a href={image('phenolab-robotic-hands.png')} target="_blank" rel="noreferrer"><img src={image('phenolab-robotic-hands.png')} loading="lazy" alt={t('Concept of two dexterous robotic hands manipulating a sample inside an instrumented glovebox','灵巧机械手在配备相机的手套箱内操作样品的概念')}/></a><figcaption><strong>02 / {t('Train for scientific manipulation','面向科研操作开展训练')}</strong>{t('Dexterous hands in a controlled workspace. R&D concept, not a deployed robot system.','受控工作空间中的灵巧机械手。研发概念，非已部署机器人系统。')}</figcaption></figure></div>
 <CaptureWorkbench lang={lang}/>
 <div className="evidence-chain">{[[t('Capture','采集'),t('Synchronized views of a demonstration','操作示范的同步多视角画面')],[t('Review','审核'),t('Link hands, objects and scientific context','关联手部、物体与科研上下文')],[t('Train & validate','训练与验证'),t('Add robot action data and supervised trials','补充机器人动作数据与受监督试验')]].map(([title,body],i)=><div key={title}><span>0{i+1}</span><h5>{title}</h5><p>{body}</p></div>)}</div>
 </div>;
}

export function RalloEvidence({lang}:Props){
 const t=text(lang),frame=useRef<HTMLIFrameElement>(null),[height,setHeight]=useState<number>();
 useEffect(()=>{const resize=(event:MessageEvent)=>{if(event.origin===location.origin&&event.source===frame.current?.contentWindow&&event.data?.type==='rallo-demo-height'&&Number.isFinite(event.data.height))setHeight(Math.max(400,Math.min(2000,event.data.height+2)))};window.addEventListener('message',resize);return()=>window.removeEventListener('message',resize)},[]);
 return <section className="rallo-evidence" aria-label={t('Interactive RALLO tracking demo','可交互 RALLO 追踪演示')}><div className="evidence-toolbar"><span>{t('Real public demo footage + tracking data','真实公开演示视频与追踪数据')}</span><a href={`/demos/rallo/?lang=${lang}`} target="_blank" rel="noreferrer">{t('Open full viewer','打开完整演示')}<ArrowUpRight size={15}/></a></div><iframe ref={frame} key={lang} style={height?{height}:undefined} title={t('RALLO motion detection and court coverage','RALLO 动作检测与球场覆盖')} src={`/demos/rallo/?lang=${lang}&embed=1`} loading="lazy" allow="fullscreen"/><p className="evidence-caption">{t('The public RALLO sample, presented in a new viewer. Player identity, visible 2D joints, observed shuttle trails and estimated court occupancy can be inspected independently.','使用 RALLO 公开样例，在新演示界面中呈现。可分别查看球员身份、可见二维关节、观测到的羽毛球轨迹与估算的球场活动分布。')}</p></section>;
}

export function OperationsWorkbench({lang}:Props){
 const t=text(lang),[view,setView]=useState('people'),[person,setPerson]=useState(0);
 const team=[{id:'DEMO-001',dept:t('Research','研发'),role:t('Researcher','研究人员'),card:true},{id:'DEMO-002',dept:t('Engineering','工程'),role:t('Equipment specialist','设备专员'),card:true},{id:'DEMO-003',dept:t('Operations','运营'),role:t('Operations coordinator','运营协调员'),card:false}];
 const nav=[{id:'people',label:t('Employees','员工'),icon:Users},{id:'equipment',label:t('Equipment','设备'),icon:CalendarDays},{id:'knowledge',label:t('Knowledge','知识'),icon:BookOpen}];
 return <section className="workbench operations-workbench" aria-label={t('Pheno operations interface recreation','Pheno 运营界面重绘')}><WorkbenchHeader lang={lang} area={t('People & operations','人员与运营')}/><div className="wb-toolbar"><div><span className="wb-kicker">{t('CONNECTED WORKPLACE','连接工作现场')}</span><h4>{t('People, access and resources. In context.','让人员、权限与资源彼此关联。')}</h4></div><span className="wb-status">{t('Fictional examples','虚构示例')}</span></div>
 <div className="wb-view-tabs">{nav.map(({id,label,icon:Icon})=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}><Icon size={16}/>{label}</button>)}</div>
 {view==='people'?<div className="operations-grid"><div><div className="wb-section-label">{t('Employee directory','员工目录')}<span>{t('3 example records','3 条示例记录')}</span></div><div className="employee-table" role="group" aria-label={t('Example employees','示例员工')}><div className="employee-row table-heading"><span>{t('Employee','员工')}</span><span>{t('Department / role','部门 / 职位')}</span><span>{t('Status','状态')}</span></div>{team.map((p,i)=><button key={p.id} className="employee-row" aria-pressed={person===i} onClick={()=>setPerson(i)} aria-label={t(`View team member ${i+1}`,`查看团队成员 ${i+1}`)}><span className="employee-name"><b>{String(i+1).padStart(2,'0')}</b><span>{t(`Team member ${i+1}`,`团队成员 ${i+1}`)}<small>{p.id}</small></span></span><span>{p.dept}<small>{p.role}</small></span><span className="employment-status">{t('Active','在职')}</span></button>)}</div></div><aside className="card-panel"><Radio size={24}/><h4>{t('RFID card binding','RFID 卡片绑定')}</h4><p>{team[person].id}</p><div className={`rfid-state ${team[person].card?'bound':''}`}>{team[person].card?<Check size={17}/>:<Radio size={17}/>} {team[person].card?t('Card linked','卡片已关联'):t('Awaiting card','等待绑卡')}</div><div className="inspector-field"><span>{t('Employee record','员工档案')}</span><strong>{t('Employment status','在职状态')}</strong></div><div className="inspector-field"><span>{t('Pheno account','Pheno 账号')}</span><strong>{t('Managed separately','独立管理')}</strong></div></aside></div>:view==='equipment'?<div className="equipment-demo"><div className="wb-section-label">{t('Equipment booking calendar','设备预约日历')}<span>{t('Illustrative day','示例日程')}</span></div><div className="booking-board">{[t('Microscope','显微镜'),t('Glovebox station','手套箱工位'),t('Characterization unit','表征设备')].map((name,i)=><div key={name}><strong>{name}</strong><span className="booking-slot">{['09:00–10:00','10:30–12:00','14:00–15:30'][i]}<b>{t(`Team member ${i+1}`,`团队成员 ${i+1}`)}</b></span><span className="booking-permission"><ShieldCheck size={15}/>{t('Permission checked','需核对权限')}</span></div>)}</div><p>{t('Bookings, equipment permissions and protected times keep shared resources coordinated.','通过设备预约、使用权限与受保护时段，协调共享资源。')}</p></div>:<div className="knowledge-demo"><div className="wb-section-label">{t('Shared files & knowledge','共享文件与知识')}</div><div className="knowledge-grid">{[[t('Weekly reports','周报'),t('A searchable record of progress','可检索的工作进展记录')],[t('Meeting files','会议文件'),t('Keep decisions near their context','让决策与上下文关联')],[t('Wiki','知识库'),t('Maintain reusable team knowledge','维护可复用的团队知识')]].map(([a,b])=><div key={a}><BookOpen size={23}/><h4>{a}</h4><p>{b}</p></div>)}</div></div>}
 <div className="wb-footer">{t('Feature-based recreation of pheno.szkl.com, using fictional records. No live HR data or account access.','基于 pheno.szkl.com 已有功能重绘，使用虚构记录；不连接真实人事数据或账号。')}</div></section>;
}

export function AgentWorkflowConcept({lang}:Props){
 const t=text(lang),[stage,setStage]=useState(0);
 const labels=[t('Request','提出需求'),t('Prepare','准备方案'),t('Review','人工审核'),t('Record','记录结果')];
 return <section className="agent-concept application-evidence"><div className="evidence-heading"><span className="eyebrow">{t('Agent-assisted operations / concept','智能体辅助运营 / 概念')}</span><h4>{t('Let agents prepare. Keep people accountable.','让智能体准备，让负责人决策。')}</h4><p>{t('An extension of the existing people, permissions and knowledge foundation: an agent prepares a booking proposal; an authorized person decides.','在既有人员、权限与知识基础上扩展：智能体准备设备预约方案，由授权人员作出决定。')}</p></div><div className="agent-demo"><div className="agent-steps">{labels.map((s,i)=><span key={s} className={stage>=i?'reached':''}><b>{i<stage?<Check size={16}/>:String(i+1).padStart(2,'0')}</b>{s}</span>)}</div><div className="agent-card"><span className="wb-kicker">{t('ILLUSTRATIVE WORKFLOW · NO LIVE ACTIONS','示意流程 · 不执行真实操作')}</span><h4>{[t('Find a suitable microscope slot.','寻找合适的显微镜时段。'),t('A proposal with its supporting context.','附有依据的预约方案。'),t('A person reviews the proposed action.','由负责人审核拟议行动。'),t('An approved action has an audit trail.','为已授权行动保留审计记录。')][stage]}</h4><p>{[t('Use the permitted equipment calendar and the requester’s access rules.','使用权限范围内的设备日历与申请人的访问规则。'),t('Suggested slot: 09:00–10:00. References: equipment availability and booking policy.','建议时段：09:00–10:00。依据：设备可用时段与预约规则。'),t('The reviewer checks the slot, the requester and the evidence before authorizing a change.','审核人核对时段、申请人与依据，再授权变更。'),t('The workflow would store the request, evidence, approver and result together. This demo has made no booking.','工作流程应同时保留需求、依据、审核人与结果。本演示未创建任何预约。')][stage]}</p><button onClick={()=>setStage((stage+1)%4)}>{stage===3?t('Replay the concept','重新演示'):t('View next step','查看下一步')}<ChevronRight size={17}/></button></div></div></section>;
}
