export type Lang = 'en' | 'zh';
export type Text = {en:string;zh:string};
export const tx = (en:string,zh:string):Text => ({en,zh});
export const copy = {
 skip:tx('Skip to content','跳转到正文'),
 home:tx('Home','首页'), applications:tx('Use cases','应用案例'), approach:tx('Why SZKL','为什么选择 SZKL'), people:tx('People','团队'), contact:tx('Let’s connect','联系我们'),
 company:tx('Shenzhen Knowledge Labs','Shenzhen Knowledge Labs'),
 eyebrow:tx('Shenzhen · Hardware + intelligence + action','深圳 · 硬件 × 智能 × 行动'),
 heroTitle:tx('AI for the physical world.','让 AI 理解真实世界，推动下一步行动。'),
 heroLead:tx('SZKL builds physical AI systems: capture real-world data, compute what it means, and turn understanding into useful action.','SZKL 构建真实世界 AI 系统：采集现场数据，计算并理解其意义，将理解转化为有用的行动。'),
 heroSub:tx('From a conversation to a court. From a lab bench to a production line.','从一段对话到一片球场，从实验台到生产线。'),
 explore:tx('Explore our applications','探索应用场景'),
 discuss:tx('Bring us a real-world problem','和我们聊聊真实问题'),
 heroFoot:tx('Product renderings and laboratory photography from our project library.','产品设计渲染与实验室照片，来自我们的项目资料。'),
 loopLabel:tx('One connected loop','同一个闭环'),
 loopTitle:tx('Reality in. Useful action out.','从真实数据，到有用行动。'),
 loopDesc:tx('The value lives in the complete system: the right capture, models grounded in context, and a workflow that changes an outcome.','价值来自完整的系统：合适的采集方式、理解场景的模型，以及真正影响结果的工作流程。'),
 stages:[
 {title:tx('Capture','采集'),sub:tx('Make the invisible recordable.','让现场信息被看见、被记录。'),body:tx('Voice devices, cameras, instruments and software connectors collect the signals that matter—at the place work and life happen.','通过语音设备、相机、仪器与软件连接，在工作和生活现场采集真正重要的信号。'),items:tx('Audio · Video · Experiments · Workflow events','音频 · 视频 · 实验数据 · 工作流程事件')},
 {title:tx('Understand','理解'),sub:tx('Turn signals into context.','将信号转化为有意义的信息。'),body:tx('Speech, vision and domain models connect observations to people, events, samples and objectives. Evidence stays linked to its source.','通过语音、视觉与领域模型，将观察结果关联到人物、事件、样品和目标，并保留证据来源。'),items:tx('Transcription · Recognition · Retrieval · Prediction','转写 · 识别 · 检索 · 预测')},
 {title:tx('Act','行动'),sub:tx('Help someone take the next step.','帮助人们决定下一步。'),body:tx('A next experiment. A follow-up task. A movement to review. The application turns understanding into a decision, a recommendation or an approved workflow.','下一轮实验、待办事项、需要复盘的动作。应用将理解转化为决策、建议或经过授权的工作流程。'),items:tx('Recommend · Review · Execute · Learn','建议 · 审核 · 执行 · 学习')}
 ],
 feedback:tx('Every reviewed outcome can inform the next cycle.','每一次经过验证的结果，都能为下一轮提供依据。'),
 appsTitle:tx('The method, in the real world.','将方法，带入真实场景。'),
 appsLead:tx('Voice, movement, experiments and enterprise operations. Each application brings the same capture–compute–act method to a different user need.','从语音、运动到实验与企业运营，用同一套采集、计算、行动的方法，服务不同的用户需求。'),
 appsLabel:tx('Applications in development','正在构建的应用'),
 capture:tx('Capture','采集'), understand:tx('Compute','计算'), act:tx('Act','行动'),
 status:tx('Where we are','当前阶段'), gallery:tx('Inside the product','走近产品'), expand:tx('Open image','查看大图'), close:tx('Close image','关闭大图'),
 imageNote:tx('Concept visual','概念示意'),
 edgeTitle:tx('The advantage is in what happens next.','竞争力，来自数据之后的行动。'),
 edgeLead:tx('A model can describe an event. A useful system knows what to do with it.','模型能够描述事件。有用的系统，还要知道如何让这些信息发挥作用。'),
 edgeBody:tx('We build around a specific job: connect the right signals, structure them for the domain, put an actionable output into the user’s workflow, and learn from the result. That combination is where a company’s distinctive advantage can grow.','我们从具体任务出发：连接合适的信号，按领域结构化数据，将可执行的输出放入使用者的工作流程，再从结果中学习。企业独有的优势，就在这个过程中逐渐积累。'),
 advantages:[
 {title:tx('Context that belongs to the task','属于具体任务的上下文'),body:tx('The sample history, the rally, the customer promise—details a generic prompt cannot supply on its own.','样品的历史、某一个回合、对客户的承诺——这些细节需要从现场和业务中获得。')},
 {title:tx('An output someone can use','真正能用的输出'),body:tx('Make the result usable at the point of work, with the evidence and next action together.','让结果出现在工作发生的地方，让证据和下一步行动相互关联。')},
 {title:tx('A feedback loop that improves','不断积累经验的闭环'),body:tx('Compare recommendations with reviewed outcomes. Keep corrections and domain expertise in the loop.','将建议与经过审核的结果进行比较，把纠正意见和专业经验纳入下一轮。')}
 ],
 rootsLabel:tx('Built close to the physical world','扎根真实场景'),
 rootsTitle:tx('From materials discovery to everyday intelligence.','从材料发现，走向更多真实世界的智能应用。'),
 rootsBody:tx('Our starting point is the practical work of materials R&D through Pheno: experiments, instruments, incomplete records and decisions that need evidence. SZKL carries that systems thinking into voice, sports and enterprise workflows.','我们的起点，是 Pheno 材料研发中的实际工作：实验、仪器、不完整的记录，以及需要证据支持的决策。SZKL 将这种系统思维延伸到语音、运动与企业工作流程。'),
 rootsSub:tx('Based in Shenzhen, we bring hardware development and AI engineering into the same product conversation.','扎根深圳，让硬件开发与 AI 工程从一开始就共同定义产品。'),
 photoCaption:tx('Laboratory photography · Pheno company materials','实验室照片 · Pheno 公司资料'),
 principlesTitle:tx('Designed for the people using it.','围绕使用者来设计。'),
 principles:[
 {title:tx('Capture with purpose','有目的地采集'),body:tx('Define what is needed, when capture happens, and who is allowed to use it.','明确需要什么数据、何时采集，以及谁有权使用。')},
 {title:tx('Keep the evidence close','保留证据关联'),body:tx('Recommendations should lead back to the relevant recording, observation or result.','让建议能够追溯到相应的录音、观察记录或实验结果。')},
 {title:tx('Keep people in control','让人保持控制权'),body:tx('Use review and explicit approval where actions affect experiments, work or other people.','当行动影响实验、业务或他人时，设置必要的审核与明确授权。')}
 ],
 teamTitle:tx('Meet the people building it.','认识背后的团队。'),
 teamLead:tx('Product, AI models and experimental systems—built by people who connect the disciplines.','连接产品、AI 模型与实验系统，让跨领域能力共同落地。'),
 bioLink:tx('View one-page profile','查看个人介绍'),
 contactTitle:tx('What could your real-world data make possible?','你的真实世界数据，还能创造什么？'),
 contactBody:tx('We’re looking for customers, domain experts and technical partners with a meaningful workflow to improve. Start with the place, the data and the decision that matters.','我们希望与客户、领域专家和技术伙伴一起，改进真正重要的工作流程。从具体场景、已有数据，以及关键决策开始聊起。'),
 mail:tx('Start a conversation','发起交流'),
 footer:tx('Physical AI. Built around useful action.','面向真实世界的 AI，让理解转化为行动。'),
 all:tx('All applications','全部应用'), back:tx('Back to SZKL','返回 SZKL'), share:tx('Copy profile link','复制介绍链接'), copied:tx('Link copied','链接已复制'),copyFail:tx('Copy the address from your browser to share this page.','请复制浏览器地址来分享此页面。'),
 print:tx('Print one-page bio','打印单页介绍'),download:tx('Save contact','保存联系人'),
 focus:tx('What I’m focused on','当前关注方向'),background:tx('Background','过往经历'),connect:tx('Good reasons to connect','欢迎交流'),links:tx('Contact & links','联系与社交'),placeholder:tx('To be added','待补充'),
 viaMichael:tx('Introduction via Michael','通过 Michael 联系'), profileNote:tx('Profile based on existing company introductions.','个人简介整理自既有公司介绍。'),
 preferences:tx('Language','语言'),chosen:tx('Selected application','当前应用'),proof:tx('Source-linked outputs. Domain-specific actions.','输出关联证据，行动贴合场景。'),
};
export const products=[
 {id:'nian',name:'Nian',cn:'念',category:tx('Voice & personal context','语音与个人上下文'),tag:tx('Hardware + app prototype','硬件与应用原型'),
 title:tx('Capture the moment. Carry the context.','记录当下，留住上下文。'),
 intro:tx('A voice recording puck and companion app that turn spoken moments into a searchable record, connected summaries and a clearer view of the day.','语音记录设备与配套应用，将口述和交流转化为可检索的记录、关联摘要，以及更清晰的一日回顾。'),
 input:tx('Button-controlled voice recording from conversations, field notes and spoken ideas.','通过实体按键控制录音，记录对话、现场笔记与口述想法。'),
 model:tx('Full transcripts, summaries of sections and a whole-day summary. Questions can be asked through the device.','全文转写、分段摘要与全天总结，并可通过设备提问。'),
 action:tx('Recall a detail, review a commitment, or draft the next task with its context. Suggested actions remain for the user to review.','回忆细节、复核约定，或结合上下文整理下一步任务，由使用者确认建议。'),
 stage:tx('Prototype: recording, app sync, layered summaries and spoken interaction. Task recommendations are an application direction.','原型具备录音、应用同步、分层总结和语音交互；任务建议是后续应用方向。'),
 image:'nian-product.png',imageAlt:tx('Nian graphite voice recorder, front, side and back product design views','Nian 石墨色语音记录设备的正面、侧面与背面设计视图'),
 caption:tx('Approved product-design rendering · enclosure concept; current prototype controls differ.','已确认的产品设计渲染 · 外观概念，当前原型的操控结构有所不同。'),
 secondary:'nian-lifestyle.png',secondaryAlt:tx('Nian pendant use concept in a working setting','工作场景中佩戴 Nian 的概念图'),
 secondaryCaption:tx('Wearable use concept · generated visualization','佩戴场景概念 · 生成式渲染'),
 takeaway:tx('For researchers, field teams and people whose important work happens in conversation.','面向研究人员、现场团队，以及在交流中完成重要工作的人。'),
 link:tx('Discuss a Nian pilot','洽谈 Nian 试用'),demo:'memory'
 },
 {id:'rallo',name:'RALLO',cn:'拉罗',category:tx('Sports & movement','运动与动作'),tag:tx('Badminton-first pilot','羽毛球优先试点'),
 title:tx('See the game. Find the next improvement.','看清比赛，找到下一步提升。'),
 intro:tx('Court cameras and computer vision turn match footage into moments players can revisit, coaches can discuss and communities can share.','球场相机与计算机视觉，将比赛视频转化为球员可回看、教练可讨论、社群可分享的精彩片段。'),
 input:tx('Court footage from fixed cameras or uploaded match videos.','固定相机采集的球场视频，或上传的比赛录像。'),
 model:tx('The current prototype combines YOLO11s-pose for player pose with TrackNetV3 for shuttle observations, plus court and temporal context. Results are being evaluated on real footage.','当前原型结合 YOLO11s-pose 球员姿态模型与 TrackNetV3 羽毛球观测模型，并纳入球场和时序信息，正通过真实视频评估结果。'),
 action:tx('Review rallies, create highlights and discuss movement with a coach. Community, leaderboards and matchmaking extend the product direction.','复盘回合、制作集锦，并与教练讨论动作。社群、排行榜和匹配约球属于产品拓展方向。'),
 stage:tx('Working public tracking demo and club pilot development. Overlays show 2D observations and estimates; automated scoring and technique recommendations remain under validation.','已提供公开追踪演示，球馆试点持续推进。叠加图层为二维观测与估算；自动计分及动作建议仍在验证中。'),
 image:'sports-concept.png',imageAlt:tx('Concept of a fixed camera observing a badminton court','固定相机采集羽毛球场视频的安装概念图'),
 caption:tx('Camera installation concept · generated visualization','相机安装概念 · 生成式渲染'),
 secondary:'rallo-screen.png',secondaryAlt:tx('Existing RALLO player-tracking interface capture with rally thumbnails','既有 RALLO 球员跟踪界面截图及回合缩略图'),
 secondaryCaption:tx('Software prototype screenshot · player tracking on sample footage','软件原型截图 · 样例视频中的球员跟踪'),
 takeaway:tx('For players, coaches and venues. Starting with badminton; designed to extend across sports.','面向球员、教练与场馆。从羽毛球出发，逐步扩展到更多运动。'),
 link:tx('Open RALLO','打开 RALLO'),demo:'sport'
 },
 {id:'phenolab',name:'Phenolab',cn:'',category:tx('Laboratories & experiments','实验室与实验'),tag:tx('Pheno Lab Data Platform · lab.szkl.com','Pheno 实验数据平台 · lab.szkl.com'),
 title:tx('A connected record of how discovery happens.','让发现的每一步，都有迹可循。'),
 intro:tx('Phenolab connects experiment design, work at the bench and instrument results. A shared record keeps the sample, the procedure and the evidence together.','Phenolab 连接实验设计、实验台操作与仪器结果，让样品、过程与证据始终关联在同一份记录中。'),
 input:tx('Capture planned and actual process conditions, sample records, observations, photos and instrument files.','采集计划与实际工艺条件、样品记录、观察、照片和仪器文件。'),
 model:tx('Structure the records around experiments and samples; review results, compare conditions and trace the supporting evidence.','围绕实验与样品组织数据，查看结果、比较条件，并追溯相关证据。'),
 action:tx('Coordinate lab work and carry reviewed evidence into the next experiment. Longer term, use reviewed demonstrations with robot action data to train scientific manipulation.','协调实验任务，将审核后的证据带入下一次实验；长期结合已审核的操作示范与机器人动作数据，训练科研操作能力。'),
 stage:tx('Phenolab is deployed at lab.szkl.com with organization sign-in. Multi-view capture, next-experiment suggestions and dexterous-hand training are R&D directions. The hardware and capture-review views here are concepts; autonomous lab operation is not claimed.','Phenolab 已部署于 lab.szkl.com，需组织账号登录。多视角采集、下一轮实验建议与灵巧手训练为研发方向。本页硬件与采集审核视图为概念，不代表已实现实验室自主操作。'),
 image:'phenolab-designer-preview.png',imageAlt:tx('Existing Phenolab Experiment Designer preview with sample data and the official Pheno logo','既有 Phenolab 实验设计器预览，包含演示数据和正式 Pheno 标识'),
 caption:tx('Experiment Designer · existing design preview, demonstration data · English interface','实验设计器 · 既有设计预览，演示数据 · 英文界面'),
 secondary:'lab-concept.png',secondaryAlt:tx('Proposed external camera capturing observations through a sealed glovebox window','拟议的外置相机，通过密封手套箱观察窗采集实验影像'),
 secondaryCaption:tx('Future capture channel · glovebox camera concept, generated visualization','未来采集方式 · 手套箱相机概念，生成式渲染'),
 takeaway:tx('For research teams connecting experimental work to reusable evidence.','面向希望将实验过程转化为可复用证据的研发团队。'),
 link:tx('Open Phenolab','打开 Phenolab'),demo:'lab'
 },
 {id:'pheno-operations',name:'Pheno',cn:'',category:tx('People & agent workflows','人员与智能体流程'),tag:tx('Operations platform · pheno.szkl.com','运营平台 · pheno.szkl.com'),
 title:tx('Connect the work. Coordinate the next action.','连接工作现场，协同下一步行动。'),
 intro:tx('Employee records, RFID cards, equipment bookings and shared knowledge provide a practical foundation for coordinated work. Agent-assisted workflows can build on that context and its permissions.','通过员工档案、RFID 卡片、设备预约与共享知识，为工作协同提供基础。智能体辅助流程可在这些上下文和权限之上扩展。'),
 input:tx('Employee and card records, equipment schedules, weekly reports, meeting files and team knowledge.','员工与卡片记录、设备日程、周报、会议文件和团队知识。'),
 model:tx('The deployed platform structures people, resources and access. A proposed agent layer would retrieve permitted context and prepare a traceable action proposal.','已部署平台组织人员、资源与访问权限；拟议的智能体层可检索权限内的上下文，准备可追溯的行动方案。'),
 action:tx('Coordinate resource use and keep records connected. In the agent concept, a person reviews proposed changes before an authorized action is recorded.','协调资源使用，关联业务记录。在智能体概念中，拟议变更先由负责人审核，再执行并记录授权行动。'),
 stage:tx('Employee, RFID, equipment and knowledge features are present in the deployed frontend. The illustrated records are fictional; the agent workflow is a proposed extension, not a claim of deployed automation.','已部署前端包含员工、RFID、设备与知识功能。所示记录为虚构演示；智能体流程为拟议扩展，并非已部署自动化能力的声明。'),
 image:'',imageAlt:tx('Recreated Pheno operations workspace with fictional employee records','使用虚构员工记录重绘的 Pheno 运营工作台'),caption:tx('Interface recreation · fictional demonstration data','界面重绘 · 虚构演示数据'),
 secondary:'',secondaryAlt:tx('Pheno operations demonstration','Pheno 运营演示'),secondaryCaption:tx('Interface concept','界面概念'),
 takeaway:tx('For research and engineering teams coordinating people, equipment and knowledge.','面向需要协同人员、设备与知识的研发和工程团队。'),
 link:tx('Open Pheno platform','打开 Pheno 平台'),demo:'operations'
 },
 {id:'pulse',name:'Pulse',cn:'',category:tx('Enterprise & industrial workflows','企业与工业工作流程'),tag:tx('Scoped customer pilots','按场景定义试点'),
 title:tx('Put intelligence where the work happens.','让智能进入真正的工作现场。'),
 intro:tx('Forward-deployed AI engineering connects a business’s data and physical operations to decisions its people can use.','通过深入现场的 AI 工程服务，将企业数据与实际运营关联起来，形成业务人员能够使用的决策依据。'),
 input:tx('Documents, work orders, operational records, sensors and relevant camera feeds—with an agreed data scope.','在约定的数据范围内，连接文档、工单、业务记录、传感器与相关视频。'),
 model:tx('Retrieval, vision and domain models interpret events against the organisation’s knowledge and workflow.','通过检索、视觉与领域模型，结合组织知识和工作流程解释业务事件。'),
 action:tx('Prepare a cited decision brief, route an exception or draft an action for approval. Integrations follow the customer’s agreed workflow.','生成附带证据的决策简报、分发异常事项，或起草待审核的行动；系统集成遵循客户确认的流程。'),
 stage:tx('Engagements are scoped around a specific workflow and measurable pilot. Capabilities and deployment boundaries are agreed per project.','围绕具体流程和可衡量的试点确定合作范围；能力与部署边界按项目约定。'),
 image:'factory-concept.jpg',imageAlt:tx('Industrial AI workflow concept in a manufacturing environment','制造场景中的工业 AI 工作流程概念图'),
 caption:tx('Manufacturing application concept · visualization from existing project materials','制造应用概念 · 来自既有项目资料的渲染图'),
 secondary:'lab-photo.jpg',secondaryAlt:tx('Laboratory equipment shown in Pheno company materials','Pheno 公司资料中的实验设备照片'),
 secondaryCaption:tx('Our scientific starting point · photography from Pheno company materials','我们的科研起点 · Pheno 公司资料中的实验室照片'),
 takeaway:tx('For manufacturers and research-led businesses ready to test AI against a real operational problem.','面向希望围绕真实运营问题验证 AI 价值的制造企业与研发型企业。'),
 link:tx('Discuss an enterprise pilot','洽谈企业 AI 试点'),demo:'enterprise'
 }
];
export const people=[
 {id:'michael',name:'Michael Liu',chinese:'刘美辰',image:'michael.jpg',role:tx('Founder · Product & business','创始人 · 产品与业务'),
 headline:tx('Building useful AI, from the physical world up.','从真实世界出发，构建有用的 AI。'),
 lead:tx('An entrepreneur connecting hardware, AI and the workflows that turn technology into products people use.','连接硬件、AI 与实际工作流程，让技术成为人们真正会用的产品。'),
 bio:tx('Michael is the Founder and CEO of Pheno Innovations and is building SZKL’s physical AI direction across enterprise systems, voice intelligence and sports vision. His focus is turning a real customer problem into an end-to-end product: what to capture, what to understand, and what action should follow.','Michael 是 Pheno Innovations 创始人兼 CEO，正在推动 SZKL 面向真实世界的 AI 布局，覆盖企业系统、语音智能与运动视觉。他关注如何将真实客户问题转化为完整产品：采集什么、理解什么，以及下一步该做什么。'),
 background:tx('Michael’s entrepreneurial experience spans China, Canada and the United States, with ventures including Apex Group and Ultiprice. He studied at the University of Alberta and now works at the intersection of scientific R&D, hardware and applied AI.','Michael 拥有中国、加拿大和美国的创业经历，曾参与创立 Apex Group 与 Ultiprice，曾就读于阿尔伯塔大学。目前专注于科研、硬件与应用 AI 的交叉领域。'),
 focus:[tx('Enterprise AI in real workflows','真实工作流程中的企业 AI'),tx('Hardware-enabled data capture','通过硬件采集现场数据'),tx('Voice, sports and scientific applications','语音、运动与科研应用')],
 connect:tx('Customers with a workflow worth improving. Technical partners building sensors and models. Founders and researchers who want to bring AI into the physical world.','欢迎希望改进具体工作流程的客户、开发传感器与模型的技术伙伴，以及希望让 AI 走进真实世界的创业者和研究人员交流。'),
 email:'mliu@szkl.com',linkedin:'https://www.linkedin.com/in/michaelmliu1/',
 contactLabel:tx('Email Michael','联系 Michael'),
 short:tx('Founder and CEO of Pheno. Building SZKL’s product direction across hardware and applied AI.','Pheno 创始人兼 CEO，推动 SZKL 硬件与应用 AI 产品方向。')
 },
 {id:'ethan',name:'Ethan Zhang, PhD',chinese:'Yixin Zhang · 博士',image:'ethan.jpg',role:tx('AI engineering · Models & systems','AI 工程 · 模型与系统'),
 headline:tx('Making real-world data useful.','让真实世界的数据发挥作用。'),
 lead:tx('Connecting data science, domain understanding and engineering to build practical AI systems.','连接数据科学、领域理解与工程能力，构建可实际应用的 AI 系统。'),
 bio:tx('Ethan (Yixin) Zhang, PhD, works across AI models and engineering, with data science experience in China and Canada spanning forecasting, recommendation and geospatial intelligence.','Ethan（Yixin）Zhang 博士从事 AI 模型与工程工作，在中国与加拿大拥有数据科学经验，涉及预测、推荐与地理空间智能。'),
 background:tx('His background includes the University of Alberta and Beihang University, and work bringing data science into operational systems. His current focus is connecting models with the data, evaluation and engineering needed for practical applications.','他的背景包括阿尔伯塔大学、北京航空航天大学的学习经历，以及将数据科学用于业务系统的实践。目前关注模型与数据、评估及工程能力的结合，推动 AI 的实际应用。'),
 focus:[tx('Vision and domain-specific models','视觉与领域模型'),tx('Structured data and prediction','结构化数据与预测'),tx('AI systems in operational workflows','实际业务流程中的 AI 系统')],
 connect:tx('Teams with real data, clear evaluation questions and a domain problem to solve together—from experiments to movement and enterprise operations.','欢迎拥有真实数据、明确评估目标和领域问题的团队交流，共同探索实验、运动与企业运营中的应用。'),
 email:'',linkedin:'',contactLabel:tx('Connect through the team','通过团队联系'),
 short:tx('Data scientist and AI engineer with experience in forecasting, recommendation and model deployment.','具备预测、推荐与模型部署经验的数据科学家及 AI 工程师。')
 },
 {id:'louis',name:'Louis Zhang, PhD',chinese:'张博士',image:'louis.jpg',role:tx('Hardware & experimental systems','硬件与实验系统'),
 headline:tx('Connecting the instrument to the intelligence.','连接仪器与智能。'),
 lead:tx('A physicist and systems designer working at the intersection of experimental platforms, data capture and applied AI.','在实验平台、数据采集与应用 AI 交叉领域开展工作的物理学博士及系统设计者。'),
 bio:tx('Louis holds a PhD in physics from Missouri University of Science and Technology and has worked on research projects supported by the US National Science Foundation. At Pheno, he has helped design AI-enabled high-throughput materials development platforms.','Louis 毕业于美国密苏里科技大学，获物理学博士学位，曾参与美国国家科学基金会支持的科研项目。在 Pheno，他参与设计了 AI 高通量材料开发平台。'),
 background:tx('His work brings experimental equipment, data collection and system design into the same workflow. At SZKL, that perspective connects what a system needs to observe with the hardware and engineering needed to capture it.','他的工作将实验设备、数据采集与系统设计融入同一工作流程。在 SZKL，这种经验将系统需要观察的内容，与实现采集所需的硬件和工程能力连接起来。'),
 focus:[tx('Experimental systems and instrumentation','实验系统与仪器'),tx('Hardware and data-capture integration','硬件与数据采集集成'),tx('AI-enabled scientific workflows','AI 支持的科研工作流程')],
 connect:tx('Hardware partners, instrument teams and researchers building reliable data capture into real experimental and operational environments.','欢迎硬件伙伴、仪器团队及研究人员交流，共同在真实实验与业务环境中构建可靠的数据采集能力。'),
 email:'',linkedin:'',contactLabel:tx('Connect through the team','通过团队联系'),
 short:tx('Physics PhD and experimental-platform designer, connecting hardware, data capture and AI.','物理学博士、实验平台设计者，连接硬件、数据采集与 AI。')
 }

];
