export type Lang = 'en' | 'zh';
export type Text = {en:string;zh:string};
export const tx = (en:string,zh:string):Text => ({en,zh});
export const copy = {
 skip:tx('Skip to content','跳转到正文'),
 home:tx('Home','首页'), applications:tx('Applications','更多应用'), approach:tx('Approach','方法与优势'), people:tx('People','团队'), contact:tx('Let’s connect','联系我们'),
 eyebrow:tx('Shenzhen · Hardware + intelligence + action','深圳 · 硬件 × 智能 × 行动'),
 heroTitle:tx('AI products for the physical world.','为真实世界，打造 AI 产品。'),
 heroLead:tx('Hardware, AI and software, built together. We’re developing Pulse for manufacturing investigations and RALLO for badminton match review. Two products, grounded in the work people do.','将硬件、AI 与软件一体化构建。我们正在开发面向制造异常排查的 Pulse，以及用于羽毛球比赛复盘的 RALLO。两个产品，始终围绕真实需求。'),
 heroSub:tx('From a lab bench to a production line. From a conversation to a court.','从实验台到生产线，从一段对话到一片球场。'),
 watchDemo:tx('Watch RALLO in action','观看 RALLO 演示'),
 discuss:tx('Discuss a pilot','洽谈试点合作'),
 methodLink:tx('How we build','我们的构建方法'),
 indexLabel:tx('What we build','我们在做什么'),
 index:[
 {num:'01',name:tx('Pulse','Pulse'),desc:tx('Evidence-backed quality investigations for manufacturing teams','面向制造团队的循证质量异常排查'),stage:tx('In development · seeking pilot partners','开发中 · 寻找试点伙伴'),href:'#pulse'},
 {num:'02',name:tx('RALLO','RALLO'),desc:tx('Court intelligence for badminton venues, players and coaches','面向羽毛球场馆、球员与教练的球场智能'),stage:tx('Recorded tracking demo available','已提供录制追踪演示'),href:'#rallo'},
 {num:'03',name:tx('Supporting applications','支撑应用'),desc:tx('Phenolab · Nian · Pheno operations','Phenolab · Nian · Pheno 运营平台'),stage:tx('Deployed platforms and prototypes','已部署平台与原型'),href:'#applications'}
 ],
 appsTitle:tx('The platform behind the products.','产品背后的平台与积累。'),
 appsLead:tx('Phenolab, Nian and our operations platform contribute scientific experience, capture hardware and workflow foundations to Pulse and RALLO.','Phenolab、Nian 与内部运营平台，为 Pulse 和 RALLO 提供科研经验、采集硬件与工作流程基础。'),
 appsLabel:tx('03 / Supporting applications','03 / 支撑应用'),
 capture:tx('Capture','采集'), understand:tx('Compute','计算'), act:tx('Act','行动'),
 status:tx('Where we are','当前阶段'), gallery:tx('Inside the product','走近产品'), expand:tx('Open image','查看大图'), close:tx('Close image','关闭大图'),
 rootsLabel:tx('Built close to the physical world','扎根真实场景'),
 rootsTitle:tx('Built from work in the real world.','从真实工作中，积累方法。'),
 rootsBody:tx('Our starting point is the practical work of materials R&D through Pheno: experiments, instruments, incomplete records and decisions that need evidence. SZKL carries that systems thinking into voice, sports and enterprise workflows.','我们的起点，是 Pheno 材料研发中的实际工作：实验、仪器、不完整的记录，以及需要证据支持的决策。SZKL 将这种系统思维延伸到语音、运动与企业工作流程。'),
 rootsSub:tx('Based in Shenzhen, we bring hardware development and AI engineering into the same product conversation.','扎根深圳，让硬件开发与 AI 工程从一开始就共同定义产品。'),
 photoCaption:tx('Materials laboratory','材料实验室'),
 principlesTitle:tx('Designed for the people using it.','围绕使用者来设计。'),
 principles:[
 {title:tx('Capture with purpose','有目的地采集'),body:tx('Define what is needed, when capture happens, and who is allowed to use it.','明确需要什么数据、何时采集，以及谁有权使用。')},
 {title:tx('Keep the evidence close','保留证据关联'),body:tx('Recommendations should lead back to the relevant recording, observation or result.','让建议能够追溯到相应的录音、观察记录或实验结果。')},
 {title:tx('Keep people in control','让人保持控制权'),body:tx('Use review and explicit approval where actions affect experiments, work or other people.','当行动影响实验、业务或他人时，设置必要的审核与明确授权。')}
 ],
 teamTitle:tx('Meet the people building it.','认识背后的团队。'),
 teamLead:tx('Product, AI models and experimental systems—built by people who connect the disciplines.','连接产品、AI 模型与实验系统，让跨领域能力共同落地。'),
 bioLink:tx('View one-page profile','查看个人介绍'),
 contactTitle:tx('What could your real-world data make possible?','你的真实世界数据，还能创造什么？'),
 contactBody:tx('We welcome manufacturing pilot partners, sports venues, domain experts and investors who care about measurable customer value. Start with the workflow, the evidence and the result worth proving.','欢迎制造业试点伙伴、运动场馆、领域专家及关注客户实际价值的投资人。从工作流程、证据与值得验证的结果开始交流。'),
 mail:tx('Start a conversation','发起交流'),
 footer:tx('Physical AI. Built around useful action.','面向真实世界的 AI，让理解转化为行动。'),
 back:tx('Back to SZKL','返回 SZKL'), share:tx('Copy profile link','复制介绍链接'), copied:tx('Link copied','链接已复制'),copyFail:tx('Copy the address from your browser to share this page.','请复制浏览器地址来分享此页面。'),
 print:tx('Print one-page bio','打印单页介绍'),download:tx('Save contact','保存联系人'),
 focus:tx('What I’m focused on','当前关注方向'),background:tx('Background','过往经历'),connect:tx('Good reasons to connect','欢迎交流'),links:tx('Contact & links','联系与社交'),placeholder:tx('To be added','待补充'),
 preferences:tx('Language','语言'),chosen:tx('Selected application','当前应用'),
};
const productDefinitions=[
 {id:'nian',name:'Nian',cn:'念',category:tx('Voice capture','语音采集'),tag:tx('Voice capture','语音采集'),
 title:tx('Capture the moment. Carry the context.','记录当下，留住上下文。'),
 intro:tx('A voice recording puck and companion app that turn spoken moments into a searchable record, connected summaries and a clearer view of the day.','语音记录设备与配套应用，将口述和交流转化为可检索的记录、关联摘要，以及更清晰的一日回顾。'),
 input:tx('Button-controlled voice recording from conversations, field notes and spoken ideas.','通过实体按键控制录音，记录对话、现场笔记与口述想法。'),
 model:tx('Full transcripts, summaries of sections and a whole-day summary. Questions can be asked through the device.','全文转写、分段摘要与全天总结，并可通过设备提问。'),
 action:tx('Recall a detail, review a commitment, or draft the next task with its context. Suggested actions remain for the user to review.','回忆细节、复核约定，或结合上下文整理下一步任务，由使用者确认建议。'),
 stage:tx('Prototype: recording, app sync, layered summaries and spoken interaction. Task recommendations are an application direction.','原型具备录音、应用同步、分层总结和语音交互；任务建议是后续应用方向。'),
 image:'nian-product.png',imageAlt:tx('Nian graphite voice recorder, front, side and back product design views','Nian 石墨色语音记录设备的正面、侧面与背面设计视图'),
 caption:tx('Nian pendant','Nian 随身吊坠'),
 secondary:'nian-lifestyle.png',secondaryAlt:tx('Nian pendant in a working setting','工作场景中佩戴 Nian'),
 secondaryCaption:tx('Wearable voice capture','随身语音采集'),
 takeaway:tx('For researchers, field teams and people whose important work happens in conversation.','面向研究人员、现场团队，以及在交流中完成重要工作的人。'),
 link:tx('Discuss a Nian pilot','洽谈 Nian 试用'),demo:'memory'
 },
 {id:'rallo',name:'RALLO',cn:'拉罗',category:tx('Sports · venue-led','运动 · 场馆触达'),tag:tx('Badminton-first pilot','羽毛球优先试点'),
 title:tx('See the game. Find the next improvement.','看清比赛，找到下一步提升。'),
 intro:tx('Court cameras and computer vision turn match footage into moments players can revisit, coaches can discuss and communities can share.','球场相机与计算机视觉，将比赛视频转化为球员可回看、教练可讨论、社群可分享的精彩片段。'),
 input:tx('Court footage from fixed cameras or uploaded match videos.','固定相机采集的球场视频，或上传的比赛录像。'),
 model:tx('The current prototype combines YOLO11s-pose for player pose with TrackNetV3 for shuttle observations, plus court and temporal context. Results are being evaluated on real footage.','当前原型结合 YOLO11s-pose 球员姿态模型与 TrackNetV3 羽毛球观测模型，并纳入球场和时序信息，正通过真实视频评估结果。'),
 action:tx('Review rallies, create highlights and discuss movement with a coach. Community, leaderboards and matchmaking extend the product direction.','复盘回合、制作集锦，并与教练讨论动作。社群、排行榜和匹配约球属于产品拓展方向。'),
 stage:tx('Working public tracking demo and club pilot development. Overlays show 2D observations and estimates; automated scoring and technique recommendations remain under validation.','已提供公开追踪演示，球馆试点持续推进。叠加图层为二维观测与估算；自动计分及动作建议仍在验证中。'),
 image:'sports-concept.png',imageAlt:tx('Fixed camera overlooking a badminton court','固定相机俯瞰羽毛球场'),
 caption:tx('Court camera placement','球场相机布置'),
 secondary:'rallo-screen.png',secondaryAlt:tx('Existing RALLO player-tracking interface capture with rally thumbnails','既有 RALLO 球员跟踪界面截图及回合缩略图'),
 secondaryCaption:tx('Player tracking','球员追踪'),
 takeaway:tx('For badminton venues, players and coaches. Prove the court experience before expanding to other sports.','面向羽毛球场馆、球员与教练，先验证球场体验，再拓展其他运动。'),
 link:tx('Open RALLO','打开 RALLO'),demo:'sport'
 },
 {id:'phenolab',name:'Phenolab',cn:'',category:tx('Laboratories & experiments','实验室与实验'),tag:tx('Pheno Lab Data Platform · lab.szkl.com','Pheno 实验数据平台 · lab.szkl.com'),
 title:tx('A connected record of how discovery happens.','让发现的每一步，都有迹可循。'),
 intro:tx('Phenolab connects experiment design, work at the bench and instrument results. A shared record keeps the sample, the procedure and the evidence together.','Phenolab 连接实验设计、实验台操作与仪器结果，让样品、过程与证据始终关联在同一份记录中。'),
 input:tx('Capture planned and actual process conditions, sample records, observations, photos and instrument files.','采集计划与实际工艺条件、样品记录、观察、照片和仪器文件。'),
 model:tx('Structure the records around experiments and samples; review results, compare conditions and trace the supporting evidence.','围绕实验与样品组织数据，查看结果、比较条件，并追溯相关证据。'),
 action:tx('Coordinate lab work and carry reviewed evidence into the next experiment. Longer term, use reviewed demonstrations with robot action data to train scientific manipulation.','协调实验任务，将审核后的证据带入下一次实验；长期结合已审核的操作示范与机器人动作数据，训练科研操作能力。'),
 stage:tx('Phenolab is deployed at lab.szkl.com with organization sign-in. Multi-view capture, next-experiment suggestions and dexterous-hand training are R&D directions. The hardware and capture-review views here are concepts; autonomous lab operation is not claimed.','Phenolab 已部署于 lab.szkl.com，需组织账号登录。多视角采集、下一轮实验建议与灵巧手训练为研发方向。本页硬件与采集审核视图为概念，不代表已实现实验室自主操作。'),
 image:'phenolab-designer-preview.png',imageAlt:tx('Existing Phenolab Experiment Designer preview with sample data and the official Pheno logo','既有 Phenolab 实验设计器预览，包含演示数据和正式 Pheno 标识'),
 caption:tx('Experiment Designer','实验设计器'),
 secondary:'lab-concept.png',secondaryAlt:tx('Proposed external camera capturing observations through a sealed glovebox window','拟议的外置相机，通过密封手套箱观察窗采集实验影像'),
 secondaryCaption:tx('Equipment capture','设备采集'),
 takeaway:tx('For research teams connecting experimental work to reusable evidence.','面向希望将实验过程转化为可复用证据的研发团队。'),
 link:tx('Open Phenolab','打开 Phenolab'),demo:'lab'
 },
 {id:'pheno-operations',name:'Pheno',cn:'',category:tx('Internal operations','内部运营'),tag:tx('Operations platform · pheno.szkl.com','运营平台 · pheno.szkl.com'),
 title:tx('Connect the work. Coordinate the next action.','连接工作现场，协同下一步行动。'),
 intro:tx('Employee records, RFID cards, equipment bookings and shared knowledge provide a practical foundation for coordinated work. Agent-assisted workflows can build on that context and its permissions.','通过员工档案、RFID 卡片、设备预约与共享知识，为工作协同提供基础。智能体辅助流程可在这些上下文和权限之上扩展。'),
 input:tx('Employee and card records, equipment schedules, weekly reports, meeting files and team knowledge.','员工与卡片记录、设备日程、周报、会议文件和团队知识。'),
 model:tx('The deployed platform structures people, resources and access. A proposed agent layer would retrieve permitted context and prepare a traceable action proposal.','已部署平台组织人员、资源与访问权限；拟议的智能体层可检索权限内的上下文，准备可追溯的行动方案。'),
 action:tx('Coordinate resource use and keep records connected. In the agent concept, a person reviews proposed changes before an authorized action is recorded.','协调资源使用，关联业务记录。在智能体概念中，拟议变更先由负责人审核，再执行并记录授权行动。'),
 stage:tx('Employee, RFID, equipment and knowledge features are present in the deployed frontend. The illustrated records are fictional; the agent workflow is a proposed extension, not a claim of deployed automation.','已部署前端包含员工、RFID、设备与知识功能。所示记录为虚构演示；智能体流程为拟议扩展，并非已部署自动化能力的声明。'),
 image:'',imageAlt:tx('Recreated Pheno operations workspace with fictional employee records','使用虚构员工记录重绘的 Pheno 运营工作台'),caption:tx('Operations workspace','运营工作台'),
 secondary:'',secondaryAlt:tx('Pheno operations demonstration','Pheno 运营演示'),secondaryCaption:tx('Operations workflow','运营流程'),
 takeaway:tx('For research and engineering teams coordinating people, equipment and knowledge.','面向需要协同人员、设备与知识的研发和工程团队。'),
 link:tx('Open Pheno platform','打开 Pheno 平台'),demo:'operations'
 },
 {id:'pulse',name:'Pulse',cn:'',category:tx('Enterprise · manufacturing','企业 · 制造业'),tag:tx('Proposed entry: SMT quality investigations','拟议切入点：SMT 质量异常排查'),
 title:tx('Make the next manufacturing decision better informed.','让下一次制造决策，更有依据。'),
 intro:tx('Pulse is being developed to help engineering teams investigate manufacturing exceptions: gather the relevant records, ask for missing context, assess possible causes and prepare a response for review.','Pulse 正围绕制造异常排查开发：汇集相关记录，询问缺失的现场信息，分析可能原因，并为工程团队准备待审核的处置方案。'),
 input:tx('Start with approved inspection results, lot and process records, and targeted operator context. Add sensors only where an important observation is missing.','从授权的检测结果、批次与工艺记录，以及针对问题补充的操作员信息开始。关键观察缺失时，再增加传感采集。'),
 model:tx('Combine retrieval, statistical checks and domain reasoning to assemble evidence, compare hypotheses and identify the next useful test.','结合检索、统计核查与领域推理，整理证据、比较假设，并确定下一项有价值的测试。'),
 action:tx('An authorised engineer reviews the proposed response. Track the result against an agreed baseline and retain the reviewed case for future investigations.','由授权工程师审核处置建议；按照约定基线跟踪结果，保留经复核的案例供后续排查使用。'),
 stage:tx('In development. Seeking pilot partners with a recurring quality issue, usable records and an agreed evaluation baseline.','开发中。寻找具有重复质量问题、可用记录，并愿意共同确定评估基线的试点伙伴。'),
 image:'factory-concept.jpg',imageAlt:tx('Industrial workflow in a manufacturing environment','制造场景中的工业工作流程'),
 caption:tx('Manufacturing workflow','制造工作流程'),
 secondary:'factory-concept.jpg',secondaryAlt:tx('Industrial workflow in a manufacturing environment','制造环境中的工业工作流程'),
 secondaryCaption:tx('Manufacturing workflow','制造工作流程'),
 takeaway:tx('For quality and process teams with a recurring exception, usable records and a measurable baseline.','面向有重复异常、可用记录及衡量基线的质量与工艺团队。'),
 link:tx('Discuss a manufacturing pilot','洽谈制造业试点'),demo:'enterprise'
 }
];
export const products=['pulse','rallo','phenolab','nian','pheno-operations'].map(id=>productDefinitions.find(p=>p.id===id)!);
export const people=[
 {id:'michael',name:'Michael Liu',chinese:'刘美辰',image:'michael-illustrated.webp',role:tx('Founder · Product & business','创始人 · 产品与业务'),
 headline:tx('Building useful AI, from the physical world up.','从真实世界出发，构建有用的 AI。'),
 lead:tx('An entrepreneur connecting hardware, AI and the workflows that turn technology into products people use.','连接硬件、AI 与实际工作流程，让技术成为人们真正会用的产品。'),
 bio:tx('Michael is the Founder and CEO of Pheno Innovations and is building SZKL’s physical AI direction across enterprise systems, voice intelligence and sports vision. His focus is turning a real customer problem into an end-to-end product: what to capture, what to understand, and what action should follow.','Michael 是 Pheno Innovations 创始人兼 CEO，正在推动 SZKL 面向真实世界的 AI 布局，覆盖企业系统、语音智能与运动视觉。他关注如何将真实客户问题转化为完整产品：采集什么、理解什么，以及下一步该做什么。'),
 background:tx('Michael’s entrepreneurial experience spans China, Canada and the United States, with ventures including Apex Group and Ultiprice. He studied at the University of Alberta and now works at the intersection of scientific R&D, hardware and applied AI.','Michael 拥有中国、加拿大和美国的创业经历，曾参与创立 Apex Group 与 Ultiprice，曾就读于阿尔伯塔大学。目前专注于科研、硬件与应用 AI 的交叉领域。'),
 focus:[tx('Enterprise AI in real workflows','真实工作流程中的企业 AI'),tx('Hardware-enabled data capture','通过硬件采集现场数据'),tx('Voice, sports and scientific applications','语音、运动与科研应用')],
 connect:tx('Customers with a workflow worth improving. Technical partners building sensors and models. Founders and researchers who want to bring AI into the physical world.','欢迎希望改进具体工作流程的客户、开发传感器与模型的技术伙伴，以及希望让 AI 走进真实世界的创业者和研究人员交流。'),
 email:'mliu@szkl.com',linkedin:'https://www.linkedin.com/in/michaelmliu1/',
 contactLabel:tx('Email Michael','联系 Michael'),
 short:tx('Founder and CEO of Pheno. Building SZKL’s product direction across hardware and applied AI.','Pheno 创始人兼 CEO，推动 SZKL 硬件与应用 AI 产品方向。')
 },
 {id:'ethan',name:'Ethan Zhang, PhD',chinese:'Yixin Zhang · 博士',image:'ethan-illustrated.webp',role:tx('AI engineering · Models & systems','AI 工程 · 模型与系统'),
 headline:tx('Making real-world data useful.','让真实世界的数据发挥作用。'),
 lead:tx('Connecting data science, domain understanding and engineering to build practical AI systems.','连接数据科学、领域理解与工程能力，构建可实际应用的 AI 系统。'),
 bio:tx('Ethan (Yixin) Zhang, PhD, works across AI models and engineering, with data science experience in China and Canada spanning forecasting, recommendation and geospatial intelligence.','Ethan（Yixin）Zhang 博士从事 AI 模型与工程工作，在中国与加拿大拥有数据科学经验，涉及预测、推荐与地理空间智能。'),
 background:tx('His background includes the University of Alberta and Beihang University, and work bringing data science into operational systems. His current focus is connecting models with the data, evaluation and engineering needed for practical applications.','他的背景包括阿尔伯塔大学、北京航空航天大学的学习经历，以及将数据科学用于业务系统的实践。目前关注模型与数据、评估及工程能力的结合，推动 AI 的实际应用。'),
 focus:[tx('Vision and domain-specific models','视觉与领域模型'),tx('Structured data and prediction','结构化数据与预测'),tx('AI systems in operational workflows','实际业务流程中的 AI 系统')],
 connect:tx('Teams with real data, clear evaluation questions and a domain problem to solve together—from experiments to movement and enterprise operations.','欢迎拥有真实数据、明确评估目标和领域问题的团队交流，共同探索实验、运动与企业运营中的应用。'),
 email:'',linkedin:'',contactLabel:tx('Connect through the team','通过团队联系'),
 short:tx('Data scientist and AI engineer with experience in forecasting, recommendation and model deployment.','具备预测、推荐与模型部署经验的数据科学家及 AI 工程师。')
 },
 {id:'louis',name:'Louis Zhang, PhD',chinese:'张博士',image:'louis-illustrated.webp',role:tx('Hardware & experimental systems','硬件与实验系统'),
 headline:tx('Connecting the instrument to the intelligence.','连接仪器与智能。'),
 lead:tx('A physicist and systems designer working at the intersection of experimental platforms, data capture and applied AI.','在实验平台、数据采集与应用 AI 交叉领域开展工作的物理学博士及系统设计者。'),
 bio:tx('Louis holds a PhD in physics from Missouri University of Science and Technology and has worked on research projects supported by the US National Science Foundation. At Pheno, he has helped design AI-enabled high-throughput materials development platforms.','Louis 毕业于美国密苏里科技大学，获物理学博士学位，曾参与美国国家科学基金会支持的科研项目。在 Pheno，他参与设计了 AI 高通量材料开发平台。'),
 background:tx('His work brings experimental equipment, data collection and system design into the same workflow. At SZKL, that perspective connects what a system needs to observe with the hardware and engineering needed to capture it.','他的工作将实验设备、数据采集与系统设计融入同一工作流程。在 SZKL，这种经验将系统需要观察的内容，与实现采集所需的硬件和工程能力连接起来。'),
 focus:[tx('Experimental systems and instrumentation','实验系统与仪器'),tx('Hardware and data-capture integration','硬件与数据采集集成'),tx('AI-enabled scientific workflows','AI 支持的科研工作流程')],
 connect:tx('Hardware partners, instrument teams and researchers building reliable data capture into real experimental and operational environments.','欢迎硬件伙伴、仪器团队及研究人员交流，共同在真实实验与业务环境中构建可靠的数据采集能力。'),
 email:'',linkedin:'',contactLabel:tx('Connect through the team','通过团队联系'),
 short:tx('Physics PhD and experimental-platform designer, connecting hardware, data capture and AI.','物理学博士、实验平台设计者，连接硬件、数据采集与 AI。')
 }

];
